### PR TITLE
Make the package work correctly + improvments

### PR DESCRIPTION
**Pull request by ldidry**
The package wasn't working properly due to the lack of php5-sqlite and a calibre library.

Improvments:
- create an empty calibre library in admin user home
- configure bbs to use this library
- change the default user to the chosen user + a custom password chosen at installation time
- fix indentation in manifest.json

### CODE REVIEW

**Comment by ldidry** [comment]
Wait a little before reviewing this, I want to have a look at #4 before.

**Comment by ldidry** [comment]
#4 fixed 🙂 

EDIT: not. Grmpf 😡

**Comment by ldidry** [comment]
Here. We're good to go with #4

**Comment by ldidry** [comment]
Ping @likeitneverwentaway

**Comment by a1ex4** [comment]
That's awesome work !! Note that not all platform compatible with YunoHost can host a Calibre library, for example the RaspberryPi. An option should be added to install BicBucStriim as a client to a remote Calibre library.

Thanks and sorry for the late response! :)

**Comment by ldidry** [comment]
Why can't you have a Calibre library on RPi? It's just SQLite.

**Comment by alexAubin** [comment]
(Bump? Thanks for the awesome work btw !)

**Comment by frju365** [comment]
euh, can we merge it ?

**Comment by frju365** [comment]
The package is not up-to-date and have many security problem because it's an old version which is used. The calibre library is possible on raspberry pi, I think, but I need a reviewer who can test the PR on a rpi. Then it's will be ok to merge it.

frju365

**Comment by frju365** [comment]
PING ? Old PR ...

**Comment by alexAubin** [comment]
What do we do with this ? The previous maintainer is not active anymore, but this PR might improve the app a lot ...

Imho in that case, the app group could take over and agree to merge this ...

**Comment by ldidry** [comment]
Ping!

**Pull request merged**
